### PR TITLE
Propate http request errors to the write side of a stream

### PR DESCRIPTION
**Pull request by dragonsinth**
Before:
```
> fsgrpcurl -max-time=3s cog list
Failed to list services: io: read/write on closed pipe
```

After:
```
> fsgrpcurl -max-time=3s cog list
failed to create a grpc channel: context deadline exceeded: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:XXXX: connect: connection refused"
```

### CODE REVIEW

**Comment by jhump** [comment]
```
> fsgrpcurl -max-time=3s cog list
failed to create a grpc channel: context deadline exceeded: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:XXXX: connect: connection refused"
```
🤮 I guess that tells us that `WithReturnConnectionError()` doesn't actually work. This is a dial issue, so the dial call should have returned this error. Apparently, it returned no error and deferred the problem to the first RPC 😭

**Review by jhump — APPROVED** [review]

**Comment by dragonsinth** [comment]
> ```
> > fsgrpcurl -max-time=3s cog list
> failed to create a grpc channel: context deadline exceeded: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:XXXX: connect: connection refused"
> ```
> 
> 🤮 I guess that tells us that `WithReturnConnectionError()` doesn't actually work. This is a dial issue, so the dial call should have returned this error. Apparently, it returned no error and deferred the problem to the first RPC 😭

This is httpgrpc... no real dial actually happens until you attempt to make a request, right?  Because it's an opaque http transport under the hood.

**Comment by jhump** [comment]
> This is httpgrpc... no real dial actually happens until you attempt to make a request, right? Because it's an opaque http transport under the hood.

🤦 doh, my bad. In that case, this is probably as good as we can do!

**Comment by dragonsinth** [comment]
I mean, if we wanted tighter integration, perhaps the httpgrpc chan could issue a test http query during the "connect" phase, just to get the Transport to make an initial conn.  Maybe like, a HEAD request to http://host:port/ ?

**Comment by jhump** [comment]
That seems overly cumbersome. I think it's fine as you just merged it.

**Comment by dragonsinth** [comment]
👍  yeah just thinking out loud :D

**Pull request merged**
